// <auto-generated />
using System;
using System.Collections.Generic;
using GLaDOS.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GLaDOS.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223121503_patch_005")]
    partial class patch_005
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GLaDOS.Domain.Discord.DiscordUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("DiscordUsers");
                });

            modelBuilder.Entity("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OldschoolRunescapeUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OldschoolRunescapeUserId");

                    b.ToTable("OldschoolRunescapeActivities");
                });

            modelBuilder.Entity("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OldschoolRunescapeUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OldschoolRunescapeUserId");

                    b.ToTable("OldschoolRunescapeStats");
                });

            modelBuilder.Entity("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DiscordUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WikiSyncEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("OldschoolRunescapeUsers");
                });

            modelBuilder.Entity("GLaDOS.Domain.OsrsWiki.OsrsWikiCollectionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.PrimitiveCollection<List<int>>("ItemIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("OldschoolRunescapeUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OldschoolRunescapeUserId")
                        .IsUnique();

                    b.ToTable("OsrsWikiCollectionLog");
                });

            modelBuilder.Entity("GLaDOS.Domain.OsrsWiki.OsrsWikiDiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("OldschoolRunescapeUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OldschoolRunescapeUserId");

                    b.ToTable("OsrsWikiDiary");
                });

            modelBuilder.Entity("GLaDOS.Domain.OsrsWiki.OsrsWikiMusic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("OldschoolRunescapeUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Song")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OldschoolRunescapeUserId");

                    b.ToTable("OsrsWikiMusic");
                });

            modelBuilder.Entity("GLaDOS.Domain.OsrsWiki.OsrsWikiQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OldschoolRunescapeUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OldschoolRunescapeUserId");

                    b.ToTable("OsrsWikiQuest");
                });

            modelBuilder.Entity("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeActivity", b =>
                {
                    b.HasOne("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", "User")
                        .WithMany("Activities")
                        .HasForeignKey("OldschoolRunescapeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeStat", b =>
                {
                    b.HasOne("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", "User")
                        .WithMany("Stats")
                        .HasForeignKey("OldschoolRunescapeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", b =>
                {
                    b.HasOne("GLaDOS.Domain.Discord.DiscordUser", "DiscordUser")
                        .WithMany("OldschoolRunescapeUsers")
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiscordUser");
                });

            modelBuilder.Entity("GLaDOS.Domain.OsrsWiki.OsrsWikiCollectionLog", b =>
                {
                    b.HasOne("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", "User")
                        .WithOne("CollectionLog")
                        .HasForeignKey("GLaDOS.Domain.OsrsWiki.OsrsWikiCollectionLog", "OldschoolRunescapeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GLaDOS.Domain.OsrsWiki.OsrsWikiDiary", b =>
                {
                    b.HasOne("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", "User")
                        .WithMany("Diaries")
                        .HasForeignKey("OldschoolRunescapeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GLaDOS.Domain.OsrsWiki.DiaryTier", "Easy", b1 =>
                        {
                            b1.Property<Guid>("OsrsWikiDiaryId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsComplete")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("easy_complete");

                            b1.PrimitiveCollection<string>("Tasks")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("easy_tasks");

                            b1.HasKey("OsrsWikiDiaryId");

                            b1.ToTable("OsrsWikiDiary");

                            b1.WithOwner()
                                .HasForeignKey("OsrsWikiDiaryId");
                        });

                    b.OwnsOne("GLaDOS.Domain.OsrsWiki.DiaryTier", "Elite", b1 =>
                        {
                            b1.Property<Guid>("OsrsWikiDiaryId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsComplete")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("elite_complete");

                            b1.PrimitiveCollection<string>("Tasks")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("elite_tasks");

                            b1.HasKey("OsrsWikiDiaryId");

                            b1.ToTable("OsrsWikiDiary");

                            b1.WithOwner()
                                .HasForeignKey("OsrsWikiDiaryId");
                        });

                    b.OwnsOne("GLaDOS.Domain.OsrsWiki.DiaryTier", "Hard", b1 =>
                        {
                            b1.Property<Guid>("OsrsWikiDiaryId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsComplete")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("hard_complete");

                            b1.PrimitiveCollection<string>("Tasks")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("hard_tasks");

                            b1.HasKey("OsrsWikiDiaryId");

                            b1.ToTable("OsrsWikiDiary");

                            b1.WithOwner()
                                .HasForeignKey("OsrsWikiDiaryId");
                        });

                    b.OwnsOne("GLaDOS.Domain.OsrsWiki.DiaryTier", "Medium", b1 =>
                        {
                            b1.Property<Guid>("OsrsWikiDiaryId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsComplete")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("medium_complete");

                            b1.PrimitiveCollection<string>("Tasks")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("medium_tasks");

                            b1.HasKey("OsrsWikiDiaryId");

                            b1.ToTable("OsrsWikiDiary");

                            b1.WithOwner()
                                .HasForeignKey("OsrsWikiDiaryId");
                        });

                    b.Navigation("Easy")
                        .IsRequired();

                    b.Navigation("Elite")
                        .IsRequired();

                    b.Navigation("Hard")
                        .IsRequired();

                    b.Navigation("Medium")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GLaDOS.Domain.OsrsWiki.OsrsWikiMusic", b =>
                {
                    b.HasOne("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", "User")
                        .WithMany("Songs")
                        .HasForeignKey("OldschoolRunescapeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GLaDOS.Domain.OsrsWiki.OsrsWikiQuest", b =>
                {
                    b.HasOne("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", "User")
                        .WithMany("Quests")
                        .HasForeignKey("OldschoolRunescapeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GLaDOS.Domain.Discord.DiscordUser", b =>
                {
                    b.Navigation("OldschoolRunescapeUsers");
                });

            modelBuilder.Entity("GLaDOS.Domain.OldschoolRunescape.OldschoolRunescapeUser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CollectionLog");

                    b.Navigation("Diaries");

                    b.Navigation("Quests");

                    b.Navigation("Songs");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
