name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_OLDSCHOOLRUNESCAPECHANNEL_ID: ${{ secrets.DISCORD_OLDSCHOOLRUNESCAPECHANNEL_ID }}
          HANGFIRE_USERNAME: ${{ secrets.HANGFIRE_USERNAME }}
          HANGFIRE_PASSWORD: ${{ secrets.HANGFIRE_PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: POSTGRES_PASSWORD,DISCORD_TOKEN,DISCORD_GUILD_ID,DISCORD_OLDSCHOOLRUNESCAPECHANNEL_ID,HANGFIRE_USERNAME,HANGFIRE_PASSWORD
          port: 22
          script: |
            cd /root/DiscordbotV2

            git fetch --all
            git reset --hard origin/main
            git pull

            rm -f .env

            echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" > .env
            echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> .env
            echo "DISCORD_GUILD_ID=$DISCORD_GUILD_ID" >> .env
            echo "DISCORD_OLDSCHOOLRUNESCAPECHANNEL_ID=$DISCORD_OLDSCHOOLRUNESCAPECHANNEL_ID" >> .env
            echo "HANGFIRE_USERNAME=$HANGFIRE_USERNAME" >> .env
            echo "HANGFIRE_PASSWORD=$HANGFIRE_PASSWORD" >> .env

            docker-compose up --build -d
            docker image prune -f
