name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/DiscordbotV2

            git fetch --all
            git reset --hard origin/main

            git pull

            rm -f .env

            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}"
            echo "DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}"
            echo "DISCORD_OLDSCHOOLRUNESCAPECHANNEL_ID=${{ secrets.DISCORD_OLDSCHOOLRUNESCAPECHANNEL_ID }}"
            echo "HANGFIRE_USERNAME=${{ secrets.HANGFIRE_USERNAME }}"
            echo "HANGFIRE_PASSWORD=${{ secrets.HANGFIRE_PASSWORD }}"

            docker-compose up --build -d
            docker image prune -f
